---
- name: Expose route for a defined service
  hosts: localhost
  vars:
    service_name: "{{ service_name_choice | default('nginx-server') }}"
    service_namespace: "{{ service_namespace_choice | default('nginx-server') }}"
    route_termination: "{{ route_termination_choice | default('insecure') }}"
  tasks:
  - name: Expose the {{ service_name }} service externally
    redhat.openshift.openshift_route:
      service: "{{ service_name }}"
      namespace: "{{ service_namespace }}"
      validate_certs: false
      termination: "{{ route_termination }}"
    register: route
  
  - debug:
      var: route