---
- name: Ensure that namespace {{ namespace_name }} is {{ namespace_state }}
  redhat.openshift.k8s:
    name: "{{ namespace_name }}"
    api_version: v1
    kind: Namespace
    state: "{{ namespace_state }}"